/* Database schema to keep the structure of entire database. */
CREATE DATABASE vet_clinic;

\c vet_clinic ;

CREATE TABLE animals(id INT GENERATED BY DEFAULT AS IDENTITY, name VARCHAR(30), date_of_birth DATE, escape_attempts INT, neutered BOOLEAN, weight_kg DECIMAL);

alter table animals add column species varchar(30);

create table owners(id int generated by default as identity primary key, full_name varchar(30), age INT);

create table species(id int generated by default as identity primary key, name varchar(30));

alter table animals add constraint pk_animal primary key (id);

alter table  animals drop column species;

alter table animals add column species_id int references species(id);

alter table animals add column owner_id int references owners(id);

create table vets(id int generated by default as identity primary key, name varchar(30), age int, date_of_graduation date);

create table specializations(id int generated by default as identity primary key, species_id int, vet_id int, foreign key (species_id) references species(id), 
foreign key (vet_id) references vets(id));

create table visits(id int generated by default as identity primary key, animal_id int, vet_id int, foreign key (animal_id) references animals(id), 
foreign key (vet_id) references vets(id));


--Vet clinic database: database performance audit

alter table visits rename visited_date  to date_of_visit; 

ALTER TABLE owners ADD COLUMN email VARCHAR(120);


-- This will add 3.594.280 visits considering you have 10 animals, 4 vets, and it will use around ~87.000 timestamps (~4min approx.)
INSERT INTO visits (animal_id, vet_id, date_of_visit) SELECT * FROM (SELECT id FROM animals) animal_ids, (SELECT id FROM vets) vets_ids, generate_series('1980-01-01'::timestamp, '2021-01-01', '4 hours') visit_timestamp;

-- This will add 2.500.000 owners with full_name = 'Owner <X>' and email = 'owner_<X>@email.com' (~2min approx.)
insert into owners (full_name, email) select 'Owner ' || generate_series(1,2500000), 'owner_' || generate_series(1,2500000) || '@mail.com';


-- This will add 3.594.280 visits considering you have 10 animals, 4 vets, and it will use around ~87.000 timestamps (~4min approx.)
INSERT INTO visits (animal_id, vet_id, date_of_visit) SELECT * FROM (SELECT id FROM animals) animal_ids, (SELECT id FROM vets) vets_ids, generate_series('1980-01-01'::timestamp, '2021-01-01', '4 hours') visit_timestamp;

-- This will add 2.500.000 owners with full_name = 'Owner <X>' and email = 'owner_<X>@email.com' (~2min approx.)
insert into owners (full_name, email) select 'Owner ' || generate_series(1,2500000), 'owner_' || generate_series(1,2500000) || '@mail.com';

create index idx_animal_id on visits (animal_id);

create index idx_vet_id on visits (vet_id);

create index idx_email on owners (email);
